---
- name: install and start httpd service
  host: All
  become: yes

- name: install httpd service
  ansible.builtin.apt:
     name: httpd
     state: present
     when: ansible_facts["os_family"] == "Debian"
- name: Start the service
  ansible.builtin.service:
   name: httpd
   state: start
   enable: yes  