---
- name: Install and run nginx
  hosts: webservers
  become: yes
  gather_facts: false
  vars:
      rpm_file: "url"

  tasks:
    - name: download the rpm file and store it locally
      block:
        - name: download the rpm_file
          ansible.builtin.get_url:
            url: '{{rpm_file}}'
            dest: /tmp/rpm
            mode: '0755'
          register: download_result
      rescue:
        - name: failed to download
          ansible.builtin.fail:
            msg: >
             Failed to download the file from {{ rpm_file }}.
             Error message: {{ download_result.msg | default('No message') }}
             Stderr: {{ download_result.stderr | default('No stderr') }}

    - name: Install nginx and start
      block:
        - name: check file exist
          ansible.builtin.stat:
            path:  /tmp/rpm
          register: file_exist
            
         
        - name: install nginx
          ansible.builtin.apt:
              name: /tmp/rpm
              state: present
              when: 
               - file_exist.stat.exists
               - ansible_facts["os_family"] == "Debian"
        - name: start nginx
          ansible.builtin.service:
               name: nginx
               state: started
               enabled: yes
      rescue:
        - name: file does not exist
          ansible.builtin.fail:
           msg: "file does not exit"
           when: not file_exist.stat.exists
  

