---
- name: install the required packages
  ansible.builtin.apt:
      name:
        - nginx
        - git
        - curl
      state: present
      update_cache: yes
      when: anisble_facts["os_family"] == "Debian"